name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md' # exclude .md files

jobs:
  test_build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rodrigorodriguescosta/branch-name@v2

      # BACKEND
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Do all the Tests
        run: |
          go test -v ./... -coverprofile=coverage.out
